### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by loojinrong** [Goldesel23/Siamese-Networks-for-One-Shot-Learning#20]
Hi, may I request for a requirement.txt file so I know what to pip install.
And are you using python 3.5 or 3.7?

Thank you.

**Comment by tensorfreitas** [comment]
It's been some years since I implemented this. You are right I should have put the requirements in the repo. Unfortunately I don't have the original implementation and the venv I used. Another user said it worked with 

!pip install keras==2.1.6
!pip install tensorflow==1.15.0

And if I'm not mistaken I was using python 3.6

**Comment by loojinrong** [comment]
thank you for your reply.
How about the cuda and cudnn version?
